## static_territories
UPDATE static_territories SET tr_name_ja="アフリカ" WHERE tr_iso_nr=2;
UPDATE static_territories SET tr_name_ja="オセアニア" WHERE tr_iso_nr=9;
UPDATE static_territories SET tr_name_ja="アメリカ" WHERE tr_iso_nr=19;
UPDATE static_territories SET tr_name_ja="アジア" WHERE tr_iso_nr=142;
UPDATE static_territories SET tr_name_ja="ヨーロッパ" WHERE tr_iso_nr=150;

UPDATE static_territories SET tr_name_ja="東アジア" WHERE tr_iso_nr=30;
UPDATE static_territories SET tr_name_ja="東南アジア" WHERE tr_iso_nr=35;
UPDATE static_territories SET tr_name_ja="中央アジア" WHERE tr_iso_nr=143;
UPDATE static_territories SET tr_name_ja="西アジア" WHERE tr_iso_nr=145;
UPDATE static_territories SET tr_name_ja="南ヨーロッパ" WHERE tr_iso_nr=39;
UPDATE static_territories SET tr_name_ja="東ヨーロッパ" WHERE tr_iso_nr=151;
UPDATE static_territories SET tr_name_ja="北ヨーロッパ" WHERE tr_iso_nr=154;
UPDATE static_territories SET tr_name_ja="西ヨーロッパ" WHERE tr_iso_nr=155;
UPDATE static_territories SET tr_name_ja="南アメリカ" WHERE tr_iso_nr=5;
UPDATE static_territories SET tr_name_ja="中央アメリカ" WHERE tr_iso_nr=13;
UPDATE static_territories SET tr_name_ja="北アメリカ" WHERE tr_iso_nr=21;
UPDATE static_territories SET tr_name_ja="カリブ" WHERE tr_iso_nr=29;
UPDATE static_territories SET tr_name_ja="西アフリカ" WHERE tr_iso_nr=11;
UPDATE static_territories SET tr_name_ja="東アフリカ" WHERE tr_iso_nr=14;
UPDATE static_territories SET tr_name_ja="北アフリカ" WHERE tr_iso_nr=15;
UPDATE static_territories SET tr_name_ja="中央アフリカ" WHERE tr_iso_nr=17;
UPDATE static_territories SET tr_name_ja="南アフリカ" WHERE tr_iso_nr=18;
UPDATE static_territories SET tr_name_ja="オーストラリア＆ニュージーランド" WHERE tr_iso_nr=53;
UPDATE static_territories SET tr_name_ja="メラネシア" WHERE tr_iso_nr=54;
UPDATE static_territories SET tr_name_ja="ミクロネシア" WHERE tr_iso_nr=57;
UPDATE static_territories SET tr_name_ja="ポリネシア" WHERE tr_iso_nr=61;
UPDATE static_territories SET tr_name_ja="南アジア" WHERE tr_iso_nr=34;


## static_countries
UPDATE static_countries SET cn_short_ja="アンドラ" WHERE cn_iso_2="AD";
UPDATE static_countries SET cn_short_ja="アラブ首長国連邦" WHERE cn_iso_2="AE";
UPDATE static_countries SET cn_short_ja="アフガニスタン" WHERE cn_iso_2="AF";
UPDATE static_countries SET cn_short_ja="アンティグア・バーブーダ" WHERE cn_iso_2="AG";
UPDATE static_countries SET cn_short_ja="アンギラ" WHERE cn_iso_2="AI";
UPDATE static_countries SET cn_short_ja="アルバニア" WHERE cn_iso_2="AL";
UPDATE static_countries SET cn_short_ja="アルメニア" WHERE cn_iso_2="AM";
UPDATE static_countries SET cn_short_ja="オランダ領アンティル" WHERE cn_iso_2="AN";
UPDATE static_countries SET cn_short_ja="アンゴラ" WHERE cn_iso_2="AO";
UPDATE static_countries SET cn_short_ja="南極大陸" WHERE cn_iso_2="AQ";
UPDATE static_countries SET cn_short_ja="アルゼンチン" WHERE cn_iso_2="AR";
UPDATE static_countries SET cn_short_ja="アメリカ領サモア" WHERE cn_iso_2="AS";
UPDATE static_countries SET cn_short_ja="オーストリア" WHERE cn_iso_2="AT";
UPDATE static_countries SET cn_short_ja="オーストラリア" WHERE cn_iso_2="AU";
UPDATE static_countries SET cn_short_ja="アルバ" WHERE cn_iso_2="AW";
UPDATE static_countries SET cn_short_ja="アゼルバイジャン" WHERE cn_iso_2="AZ";
UPDATE static_countries SET cn_short_ja="ボスニア・ヘルツェゴビナ" WHERE cn_iso_2="BA";
UPDATE static_countries SET cn_short_ja="バルバドス" WHERE cn_iso_2="BB";
UPDATE static_countries SET cn_short_ja="バングラデシュ" WHERE cn_iso_2="BD";
UPDATE static_countries SET cn_short_ja="ベルギー" WHERE cn_iso_2="BE";
UPDATE static_countries SET cn_short_ja="ブルキナファソ" WHERE cn_iso_2="BF";
UPDATE static_countries SET cn_short_ja="ブルガリア" WHERE cn_iso_2="BG";
UPDATE static_countries SET cn_short_ja="バーレーン" WHERE cn_iso_2="BH";
UPDATE static_countries SET cn_short_ja="ブルンジ" WHERE cn_iso_2="BI";
UPDATE static_countries SET cn_short_ja="ベニン" WHERE cn_iso_2="BJ";
UPDATE static_countries SET cn_short_ja="バミューダ" WHERE cn_iso_2="BM";
UPDATE static_countries SET cn_short_ja="ブルネイ" WHERE cn_iso_2="BN";
UPDATE static_countries SET cn_short_ja="ボリビア" WHERE cn_iso_2="BO";
UPDATE static_countries SET cn_short_ja="ブラジル" WHERE cn_iso_2="BR";
UPDATE static_countries SET cn_short_ja="バハマ" WHERE cn_iso_2="BS";
UPDATE static_countries SET cn_short_ja="ブータン" WHERE cn_iso_2="BT";
UPDATE static_countries SET cn_short_ja="ブーヴェ島" WHERE cn_iso_2="BV";
UPDATE static_countries SET cn_short_ja="ボツワナ" WHERE cn_iso_2="BW";
UPDATE static_countries SET cn_short_ja="ベラルーシ" WHERE cn_iso_2="BY";
UPDATE static_countries SET cn_short_ja="ベリーズ" WHERE cn_iso_2="BZ";
UPDATE static_countries SET cn_short_ja="カナダ" WHERE cn_iso_2="CA";
UPDATE static_countries SET cn_short_ja="クック（Keeling）諸島" WHERE cn_iso_2="CC";
UPDATE static_countries SET cn_short_ja="コンゴ民主共和国" WHERE cn_iso_2="CD";
UPDATE static_countries SET cn_short_ja="中央アフリカ共和国" WHERE cn_iso_2="CF";
UPDATE static_countries SET cn_short_ja="コンゴ共和国" WHERE cn_iso_2="CG";
UPDATE static_countries SET cn_short_ja="スイス" WHERE cn_iso_2="CH";
UPDATE static_countries SET cn_short_ja="コートジボワール" WHERE cn_iso_2="CI";
UPDATE static_countries SET cn_short_ja="クック諸島" WHERE cn_iso_2="CK";
UPDATE static_countries SET cn_short_ja="チリ" WHERE cn_iso_2="CL";
UPDATE static_countries SET cn_short_ja="カメルーン" WHERE cn_iso_2="CM";
UPDATE static_countries SET cn_short_ja="中国" WHERE cn_iso_2="CN";
UPDATE static_countries SET cn_short_ja="コロンビア" WHERE cn_iso_2="CO";
UPDATE static_countries SET cn_short_ja="コスタリカ" WHERE cn_iso_2="CR";
UPDATE static_countries SET cn_short_ja="キューバ" WHERE cn_iso_2="CU";
UPDATE static_countries SET cn_short_ja="カーボヴェルデ" WHERE cn_iso_2="CV";
UPDATE static_countries SET cn_short_ja="クリスマス諸島" WHERE cn_iso_2="CX";
UPDATE static_countries SET cn_short_ja="キプロス" WHERE cn_iso_2="CY";
UPDATE static_countries SET cn_short_ja="チェコ共和国" WHERE cn_iso_2="CZ";
UPDATE static_countries SET cn_short_ja="ドイツ" WHERE cn_iso_2="DE";
UPDATE static_countries SET cn_short_ja="ジブチ" WHERE cn_iso_2="DJ";
UPDATE static_countries SET cn_short_ja="デンマーク" WHERE cn_iso_2="DK";
UPDATE static_countries SET cn_short_ja="ドミニカ国" WHERE cn_iso_2="DM";
UPDATE static_countries SET cn_short_ja="ドミニカ共和国" WHERE cn_iso_2="DO";
UPDATE static_countries SET cn_short_ja="アルジェリア" WHERE cn_iso_2="DZ";
UPDATE static_countries SET cn_short_ja="エクアドル" WHERE cn_iso_2="EC";
UPDATE static_countries SET cn_short_ja="エストニア" WHERE cn_iso_2="EE";
UPDATE static_countries SET cn_short_ja="エジプト" WHERE cn_iso_2="EG";
UPDATE static_countries SET cn_short_ja="西サハラ" WHERE cn_iso_2="EH";
UPDATE static_countries SET cn_short_ja="エリトリア" WHERE cn_iso_2="ER";
UPDATE static_countries SET cn_short_ja="スペイン" WHERE cn_iso_2="ES";
UPDATE static_countries SET cn_short_ja="エチオピア" WHERE cn_iso_2="ET";
UPDATE static_countries SET cn_short_ja="フィンランド" WHERE cn_iso_2="FI";
UPDATE static_countries SET cn_short_ja="フィジー" WHERE cn_iso_2="FJ";
UPDATE static_countries SET cn_short_ja="フォークランド（マルビナス）諸島" WHERE cn_iso_2="FK";
UPDATE static_countries SET cn_short_ja="ミクロネシア" WHERE cn_iso_2="FM";
UPDATE static_countries SET cn_short_ja="フェロー諸島e" WHERE cn_iso_2="FO";
UPDATE static_countries SET cn_short_ja="フランス" WHERE cn_iso_2="FR";
UPDATE static_countries SET cn_short_ja="ガボン" WHERE cn_iso_2="GA";
UPDATE static_countries SET cn_short_ja="英国" WHERE cn_iso_2="GB";
UPDATE static_countries SET cn_short_ja="グレナダ" WHERE cn_iso_2="GD";
UPDATE static_countries SET cn_short_ja="グルジア" WHERE cn_iso_2="GE";
UPDATE static_countries SET cn_short_ja="フランス領ギアナ" WHERE cn_iso_2="GF";
UPDATE static_countries SET cn_short_ja="ガーナ" WHERE cn_iso_2="GH";
UPDATE static_countries SET cn_short_ja="ジブラルタル" WHERE cn_iso_2="GI";
UPDATE static_countries SET cn_short_ja="グリーンランド" WHERE cn_iso_2="GL";
UPDATE static_countries SET cn_short_ja="ガンビア" WHERE cn_iso_2="GM";
UPDATE static_countries SET cn_short_ja="ギニア共和国" WHERE cn_iso_2="GN";
UPDATE static_countries SET cn_short_ja="グアダルーペ" WHERE cn_iso_2="GP";
UPDATE static_countries SET cn_short_ja="赤道ギニア共和国" WHERE cn_iso_2="GQ";
UPDATE static_countries SET cn_short_ja="ギリシャ" WHERE cn_iso_2="GR";
UPDATE static_countries SET cn_short_ja="サウスジョージア・サウスサンドウィッチ諸島" WHERE cn_iso_2="GS";
UPDATE static_countries SET cn_short_ja="グアテマラ" WHERE cn_iso_2="GT";
UPDATE static_countries SET cn_short_ja="グアム" WHERE cn_iso_2="GU";
UPDATE static_countries SET cn_short_ja="ギネアビサウ" WHERE cn_iso_2="GW";
UPDATE static_countries SET cn_short_ja="ガイアナ" WHERE cn_iso_2="GY";
UPDATE static_countries SET cn_short_ja="香港-中国特別行政区" WHERE cn_iso_2="HK";
UPDATE static_countries SET cn_short_ja="ホンジュラス" WHERE cn_iso_2="HN";
UPDATE static_countries SET cn_short_ja="クロアチア" WHERE cn_iso_2="HR";
UPDATE static_countries SET cn_short_ja="ハイチ" WHERE cn_iso_2="HT";
UPDATE static_countries SET cn_short_ja="ハンガリー" WHERE cn_iso_2="HU";
UPDATE static_countries SET cn_short_ja="インドネシア" WHERE cn_iso_2="ID";
UPDATE static_countries SET cn_short_ja="アイルランド" WHERE cn_iso_2="IE";
UPDATE static_countries SET cn_short_ja="イスラエルl" WHERE cn_iso_2="IL";
UPDATE static_countries SET cn_short_ja="インド" WHERE cn_iso_2="IN";
UPDATE static_countries SET cn_short_ja="英国領インド洋地域" WHERE cn_iso_2="IO";
UPDATE static_countries SET cn_short_ja="イラク" WHERE cn_iso_2="IQ";
UPDATE static_countries SET cn_short_ja="イラン" WHERE cn_iso_2="IR";
UPDATE static_countries SET cn_short_ja="アイスランド" WHERE cn_iso_2="IS";
UPDATE static_countries SET cn_short_ja="イタリア" WHERE cn_iso_2="IT";
UPDATE static_countries SET cn_short_ja="ジャマイカ" WHERE cn_iso_2="JM";
UPDATE static_countries SET cn_short_ja="ヨルダン" WHERE cn_iso_2="JO";
UPDATE static_countries SET cn_short_ja="日本" WHERE cn_iso_2="JP";
UPDATE static_countries SET cn_short_ja="ケニア" WHERE cn_iso_2="KE";
UPDATE static_countries SET cn_short_ja="キルギス共和国" WHERE cn_iso_2="KG";
UPDATE static_countries SET cn_short_ja="カンボジア" WHERE cn_iso_2="KH";
UPDATE static_countries SET cn_short_ja="キリバス共和国i" WHERE cn_iso_2="KI";
UPDATE static_countries SET cn_short_ja="コモロ連合" WHERE cn_iso_2="KM";
UPDATE static_countries SET cn_short_ja="セントクリストファー・ネービス" WHERE cn_iso_2="KN";
UPDATE static_countries SET cn_short_ja="北朝鮮" WHERE cn_iso_2="KP";
UPDATE static_countries SET cn_short_ja="韓国" WHERE cn_iso_2="KR";
UPDATE static_countries SET cn_short_ja="クウェート" WHERE cn_iso_2="KW";
UPDATE static_countries SET cn_short_ja="カイマン諸島" WHERE cn_iso_2="KY";
UPDATE static_countries SET cn_short_ja="カザフスタン" WHERE cn_iso_2="KZ";
UPDATE static_countries SET cn_short_ja="ラオス" WHERE cn_iso_2="LA";
UPDATE static_countries SET cn_short_ja="レバノン" WHERE cn_iso_2="LB";
UPDATE static_countries SET cn_short_ja="セントルシア" WHERE cn_iso_2="LC";
UPDATE static_countries SET cn_short_ja="リヒテンシュタイン" WHERE cn_iso_2="LI";
UPDATE static_countries SET cn_short_ja="スリランカ" WHERE cn_iso_2="LK";
UPDATE static_countries SET cn_short_ja="リベリア" WHERE cn_iso_2="LR";
UPDATE static_countries SET cn_short_ja="レソト" WHERE cn_iso_2="LS";
UPDATE static_countries SET cn_short_ja="リトアニア" WHERE cn_iso_2="LT";
UPDATE static_countries SET cn_short_ja="ルクセンブルグ" WHERE cn_iso_2="LU";
UPDATE static_countries SET cn_short_ja="ラトニア" WHERE cn_iso_2="LV";
UPDATE static_countries SET cn_short_ja="リビア" WHERE cn_iso_2="LY";
UPDATE static_countries SET cn_short_ja="モロッコ" WHERE cn_iso_2="MA";
UPDATE static_countries SET cn_short_ja="モナコ" WHERE cn_iso_2="MC";
UPDATE static_countries SET cn_short_ja="モルドバ" WHERE cn_iso_2="MD";
UPDATE static_countries SET cn_short_ja="マダカスカル" WHERE cn_iso_2="MG";
UPDATE static_countries SET cn_short_ja="マーシャル諸島" WHERE cn_iso_2="MH";
UPDATE static_countries SET cn_short_ja="マケドニア旧ユーゴスラビア共和国" WHERE cn_iso_2="MK";
UPDATE static_countries SET cn_short_ja="マリ" WHERE cn_iso_2="ML";
UPDATE static_countries SET cn_short_ja="ミャンマー" WHERE cn_iso_2="MM";
UPDATE static_countries SET cn_short_ja="モンゴル" WHERE cn_iso_2="MN";
UPDATE static_countries SET cn_short_ja="マカオ-中国特別行政区" WHERE cn_iso_2="MO";
UPDATE static_countries SET cn_short_ja="北マリアナ諸島" WHERE cn_iso_2="MP";
UPDATE static_countries SET cn_short_ja="マルティニーク" WHERE cn_iso_2="MQ";
UPDATE static_countries SET cn_short_ja="モーリタニア" WHERE cn_iso_2="MR";
UPDATE static_countries SET cn_short_ja="モントセラト島" WHERE cn_iso_2="MS";
UPDATE static_countries SET cn_short_ja="マルタ" WHERE cn_iso_2="MT";
UPDATE static_countries SET cn_short_ja="モーリシャス" WHERE cn_iso_2="MU";
UPDATE static_countries SET cn_short_ja="モルジブ" WHERE cn_iso_2="MV";
UPDATE static_countries SET cn_short_ja="マラウィ" WHERE cn_iso_2="MW";
UPDATE static_countries SET cn_short_ja="メキシコ" WHERE cn_iso_2="MX";
UPDATE static_countries SET cn_short_ja="マレーシア" WHERE cn_iso_2="MY";
UPDATE static_countries SET cn_short_ja="モザンビーク" WHERE cn_iso_2="MZ";
UPDATE static_countries SET cn_short_ja="ナミビア" WHERE cn_iso_2="NA";
UPDATE static_countries SET cn_short_ja="ニューカレドニア" WHERE cn_iso_2="NC";
UPDATE static_countries SET cn_short_ja="ニジェール" WHERE cn_iso_2="NE";
UPDATE static_countries SET cn_short_ja="ノーフォーク島" WHERE cn_iso_2="NF";
UPDATE static_countries SET cn_short_ja="ナイジェリア" WHERE cn_iso_2="NG";
UPDATE static_countries SET cn_short_ja="ニカラグア" WHERE cn_iso_2="NI";
UPDATE static_countries SET cn_short_ja="オランダ" WHERE cn_iso_2="NL";
UPDATE static_countries SET cn_short_ja="ノルウェー" WHERE cn_iso_2="NO";
UPDATE static_countries SET cn_short_ja="ネパール" WHERE cn_iso_2="NP";
UPDATE static_countries SET cn_short_ja="ナウル" WHERE cn_iso_2="NR";
UPDATE static_countries SET cn_short_ja="ニウエ島" WHERE cn_iso_2="NU";
UPDATE static_countries SET cn_short_ja="ニュージーランド" WHERE cn_iso_2="NZ";
UPDATE static_countries SET cn_short_ja="オマーン" WHERE cn_iso_2="OM";
UPDATE static_countries SET cn_short_ja="パナマ" WHERE cn_iso_2="PA";
UPDATE static_countries SET cn_short_ja="ペルー" WHERE cn_iso_2="PE";
UPDATE static_countries SET cn_short_ja="フランス領ポリネシア" WHERE cn_iso_2="PF";
UPDATE static_countries SET cn_short_ja="パプアニューギニア" WHERE cn_iso_2="PG";
UPDATE static_countries SET cn_short_ja="フィリピン" WHERE cn_iso_2="PH";
UPDATE static_countries SET cn_short_ja="パキスタン" WHERE cn_iso_2="PK";
UPDATE static_countries SET cn_short_ja="ポーランド" WHERE cn_iso_2="PL";
UPDATE static_countries SET cn_short_ja="サンピエール島・ミクロン島" WHERE cn_iso_2="PM";
UPDATE static_countries SET cn_short_ja="ピトケアン諸島" WHERE cn_iso_2="PN";
UPDATE static_countries SET cn_short_ja="プエルトリコ" WHERE cn_iso_2="PR";
UPDATE static_countries SET cn_short_ja="ポルトガル" WHERE cn_iso_2="PT";
UPDATE static_countries SET cn_short_ja="パラオ" WHERE cn_iso_2="PW";
UPDATE static_countries SET cn_short_ja="パラグアイ" WHERE cn_iso_2="PY";
UPDATE static_countries SET cn_short_ja="カタール" WHERE cn_iso_2="QA";
UPDATE static_countries SET cn_short_ja="レユニオン" WHERE cn_iso_2="RE";
UPDATE static_countries SET cn_short_ja="ルーマニア" WHERE cn_iso_2="RO";
UPDATE static_countries SET cn_short_ja="ロシア" WHERE cn_iso_2="RU";
UPDATE static_countries SET cn_short_ja="ルアンダ" WHERE cn_iso_2="RW";
UPDATE static_countries SET cn_short_ja="サウジアラビア" WHERE cn_iso_2="SA";
UPDATE static_countries SET cn_short_ja="ソロモン諸島" WHERE cn_iso_2="SB";
UPDATE static_countries SET cn_short_ja="セイシェル" WHERE cn_iso_2="SC";
UPDATE static_countries SET cn_short_ja="スーダン" WHERE cn_iso_2="SD";
UPDATE static_countries SET cn_short_ja="スウェーデン" WHERE cn_iso_2="SE";
UPDATE static_countries SET cn_short_ja="シンガポール" WHERE cn_iso_2="SG";
UPDATE static_countries SET cn_short_ja="セントヘレナ" WHERE cn_iso_2="SH";
UPDATE static_countries SET cn_short_ja="スロベニア" WHERE cn_iso_2="SI";
UPDATE static_countries SET cn_short_ja="スヴェールバル諸島・ヤンマイエン島" WHERE cn_iso_2="SJ";
UPDATE static_countries SET cn_short_ja="スロバキア" WHERE cn_iso_2="SK";
UPDATE static_countries SET cn_short_ja="シエラレオーネ" WHERE cn_iso_2="SL";
UPDATE static_countries SET cn_short_ja="サンマリノ" WHERE cn_iso_2="SM";
UPDATE static_countries SET cn_short_ja="セネガル" WHERE cn_iso_2="SN";
UPDATE static_countries SET cn_short_ja="ソマリア" WHERE cn_iso_2="SO";
UPDATE static_countries SET cn_short_ja="スリナム" WHERE cn_iso_2="SR";
UPDATE static_countries SET cn_short_ja="サントメ・プリンシペ民主共和国" WHERE cn_iso_2="ST";
UPDATE static_countries SET cn_short_ja="エルサルバドル" WHERE cn_iso_2="SV";
UPDATE static_countries SET cn_short_ja="シリア" WHERE cn_iso_2="SY";
UPDATE static_countries SET cn_short_ja="スワジランド" WHERE cn_iso_2="SZ";
UPDATE static_countries SET cn_short_ja="タークス・カイコス諸島" WHERE cn_iso_2="TC";
UPDATE static_countries SET cn_short_ja="チャド" WHERE cn_iso_2="TD";
UPDATE static_countries SET cn_short_ja="フランス領南方・南極地域" WHERE cn_iso_2="TF";
UPDATE static_countries SET cn_short_ja="トーゴ" WHERE cn_iso_2="TG";
UPDATE static_countries SET cn_short_ja="タイ" WHERE cn_iso_2="TH";
UPDATE static_countries SET cn_short_ja="タジキスタン" WHERE cn_iso_2="TJ";
UPDATE static_countries SET cn_short_ja="トケラウ諸島" WHERE cn_iso_2="TK";
UPDATE static_countries SET cn_short_ja="トルクメニスタン" WHERE cn_iso_2="TM";
UPDATE static_countries SET cn_short_ja="チュニジア" WHERE cn_iso_2="TN";
UPDATE static_countries SET cn_short_ja="トンガ" WHERE cn_iso_2="TO";
UPDATE static_countries SET cn_short_ja="東チモール" WHERE cn_iso_2="TL";
UPDATE static_countries SET cn_short_ja="トルコ" WHERE cn_iso_2="TR";
UPDATE static_countries SET cn_short_ja="トニダードトバゴ" WHERE cn_iso_2="TT";
UPDATE static_countries SET cn_short_ja="ツバル" WHERE cn_iso_2="TV";
UPDATE static_countries SET cn_short_ja="台湾" WHERE cn_iso_2="TW";
UPDATE static_countries SET cn_short_ja="タンザニア" WHERE cn_iso_2="TZ";
UPDATE static_countries SET cn_short_ja="ウクライナ" WHERE cn_iso_2="UA";
UPDATE static_countries SET cn_short_ja="ウガンダ" WHERE cn_iso_2="UG";
UPDATE static_countries SET cn_short_ja="アメリカ領太平洋諸島" WHERE cn_iso_2="UM";
UPDATE static_countries SET cn_short_ja="米国" WHERE cn_iso_2="US";
UPDATE static_countries SET cn_short_ja="ウルグアイ" WHERE cn_iso_2="UY";
UPDATE static_countries SET cn_short_ja="ウズベキスタン" WHERE cn_iso_2="UZ";
UPDATE static_countries SET cn_short_ja="バチカン市国" WHERE cn_iso_2="VA";
UPDATE static_countries SET cn_short_ja="セントビンセント・グレナディーン諸島" WHERE cn_iso_2="VC";
UPDATE static_countries SET cn_short_ja="ベネズエラ" WHERE cn_iso_2="VE";
UPDATE static_countries SET cn_short_ja="英国領ヴァージン諸島" WHERE cn_iso_2="VG";
UPDATE static_countries SET cn_short_ja="アメリカ領ヴァージン諸島" WHERE cn_iso_2="VI";
UPDATE static_countries SET cn_short_ja="ベトナム" WHERE cn_iso_2="VN";
UPDATE static_countries SET cn_short_ja="バヌアツ" WHERE cn_iso_2="VU";
UPDATE static_countries SET cn_short_ja="ワリス・フテュナ諸島" WHERE cn_iso_2="WF";
UPDATE static_countries SET cn_short_ja="サモア" WHERE cn_iso_2="WS";
UPDATE static_countries SET cn_short_ja="イエメン" WHERE cn_iso_2="YE";
UPDATE static_countries SET cn_short_ja="マイヨット島" WHERE cn_iso_2="YT";
UPDATE static_countries SET cn_short_ja="南アフリカ" WHERE cn_iso_2="ZA";
UPDATE static_countries SET cn_short_ja="ザンビア" WHERE cn_iso_2="ZM";
UPDATE static_countries SET cn_short_ja="ジンバブエ" WHERE cn_iso_2="ZW";
UPDATE static_countries SET cn_short_ja="パレスチナ自治区" WHERE cn_iso_2="PS";
UPDATE static_countries SET cn_short_ja="セルビアモンテネグロ" WHERE cn_iso_2="CS";
UPDATE static_countries SET cn_short_ja="アランド島" WHERE cn_iso_2="AX";
UPDATE static_countries SET cn_short_ja="ハード島・マクドナルド諸島" WHERE cn_iso_2="HM";
UPDATE static_countries SET cn_short_ja="モンテネグロ" WHERE cn_iso_2="ME";
UPDATE static_countries SET cn_short_ja="セルビア共和国" WHERE cn_iso_2="RS";
UPDATE static_countries SET cn_short_ja="ジャージー" WHERE cn_iso_2="JE";
UPDATE static_countries SET cn_short_ja="ガーンジー" WHERE cn_iso_2="GG";
UPDATE static_countries SET cn_short_ja="マン島" WHERE cn_iso_2="IM";
UPDATE static_countries SET cn_short_ja="セント・マーチン島" WHERE cn_iso_2="MF";
UPDATE static_countries SET cn_short_ja="サン・バルテルミー島" WHERE cn_iso_2="BL";
UPDATE static_countries SET cn_short_ja="ボネール、シント・ユースタティウスおよびサバ" WHERE cn_iso_2="BQ";
UPDATE static_countries SET cn_short_ja="キュラソー" WHERE cn_iso_2="CW";
UPDATE static_countries SET cn_short_ja="シント・マールテン" WHERE cn_iso_2="SX";
UPDATE static_countries SET cn_short_ja="南スーダン共和国" WHERE cn_iso_2="SS";
UPDATE static_countries SET cn_short_ja="コソボ共和国" WHERE cn_iso_2="XK";

## static_languages
UPDATE static_languages SET lg_name_ja="アブハーズ語" WHERE lg_iso_2="AB" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アファル語" WHERE lg_iso_2="AA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アフリカーンス語" WHERE lg_iso_2="AF" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アルバニア語" WHERE lg_iso_2="SQ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アムハラ語" WHERE lg_iso_2="AM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アラビア語" WHERE lg_iso_2="AR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アルメニア語" WHERE lg_iso_2="HY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アッサム語" WHERE lg_iso_2="AS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アイマラ語" WHERE lg_iso_2="AY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アゼルバイジャン語" WHERE lg_iso_2="AZ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="バシキール語学" WHERE lg_iso_2="BA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="バスク語" WHERE lg_iso_2="EU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ベンガル語" WHERE lg_iso_2="BN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ブータン語" WHERE lg_iso_2="DZ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ビハール語" WHERE lg_iso_2="BH" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ビスラマ語" WHERE lg_iso_2="BI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ブルトン語" WHERE lg_iso_2="BR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ブルガリア語" WHERE lg_iso_2="BG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ビルマ語" WHERE lg_iso_2="MY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ベラルーシ語" WHERE lg_iso_2="BE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クメール語" WHERE lg_iso_2="KM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="カタルーニャ語" WHERE lg_iso_2="CA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チワン語" WHERE lg_iso_2="ZA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="中国語" WHERE lg_iso_2="ZH" AND lg_country_iso_2="HK";
UPDATE static_languages SET lg_name_ja="コルシカ語" WHERE lg_iso_2="CO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クロアチア語" WHERE lg_iso_2="HR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チェコ語" WHERE lg_iso_2="CS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="デンマーク語" WHERE lg_iso_2="DA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オランダ語" WHERE lg_iso_2="NL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="英語" WHERE lg_iso_2="EN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="エスペラント語" WHERE lg_iso_2="EO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="エストニア語" WHERE lg_iso_2="ET" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フェロー語" WHERE lg_iso_2="FO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ペルシャ語" WHERE lg_iso_2="FA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フィジー語" WHERE lg_iso_2="FJ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フィンランド語" WHERE lg_iso_2="FI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フランス語" WHERE lg_iso_2="FR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フリジア語" WHERE lg_iso_2="FY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ガリシア語" WHERE lg_iso_2="GL" AND lg_country_iso_2="ES";
UPDATE static_languages SET lg_name_ja="スコットランド・ゲール語" WHERE lg_iso_2="GD" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マン島ゲール語" WHERE lg_iso_2="GV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="グルジア語" WHERE lg_iso_2="KA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ドイツ語" WHERE lg_iso_2="DE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ギリシャ語" WHERE lg_iso_2="EL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="グリーンランド語" WHERE lg_iso_2="KL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="グアラニー語" WHERE lg_iso_2="GN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クラジャート語" WHERE lg_iso_2="GU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ハウサ語" WHERE lg_iso_2="HA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ヘブライ語" WHERE lg_iso_2="HE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ヒンディー語" WHERE lg_iso_2="HI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ハンガリー語" WHERE lg_iso_2="HU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アイスランド語" WHERE lg_iso_2="IS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="インドネシア語" WHERE lg_iso_2="ID" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イヌクティトット（イヌイット）語" WHERE lg_iso_2="IU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イヌピアック語" WHERE lg_iso_2="IK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アイルランド語" WHERE lg_iso_2="GA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イタリア語" WHERE lg_iso_2="IT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="日本語" WHERE lg_iso_2="JA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="カナラ語" WHERE lg_iso_2="KN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="カシミール語" WHERE lg_iso_2="KS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="カザフ語" WHERE lg_iso_2="KK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="キニャルワンダ語" WHERE lg_iso_2="RW" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="キルギス語" WHERE lg_iso_2="KY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="キルンディ語" WHERE lg_iso_2="RN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="韓国語" WHERE lg_iso_2="KO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クルド語" WHERE lg_iso_2="KU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ラオス語" WHERE lg_iso_2="LO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ラトニア語" WHERE lg_iso_2="LV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="リンガラ語" WHERE lg_iso_2="LN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="リトアニア語" WHERE lg_iso_2="LT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マケドニア語" WHERE lg_iso_2="MK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マダガスカル語" WHERE lg_iso_2="MG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マレーシア語" WHERE lg_iso_2="MS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マラヤーラム語" WHERE lg_iso_2="ML" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マルタ語" WHERE lg_iso_2="MT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マオリ語" WHERE lg_iso_2="MI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マラーティー語" WHERE lg_iso_2="MR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="モルドバ語" WHERE lg_iso_2="MO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="モンゴル語" WHERE lg_iso_2="MN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ナウル語" WHERE lg_iso_2="NA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ネパール語" WHERE lg_iso_2="NE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ノルウェー語" WHERE lg_iso_2="NO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オクシタン語（1500年以降）" WHERE lg_iso_2="OC" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オリヤー語" WHERE lg_iso_2="OR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オロモ語" WHERE lg_iso_2="OM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="パシュトゥー語" WHERE lg_iso_2="PS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ポーランド語" WHERE lg_iso_2="PL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ポルトガル語" WHERE lg_iso_2="PT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="パンジャブ語" WHERE lg_iso_2="PA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ケチュア語" WHERE lg_iso_2="QU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="レト・ロマン語" WHERE lg_iso_2="RM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ルーマニア語" WHERE lg_iso_2="RO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ロシア語" WHERE lg_iso_2="RU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="サモア語" WHERE lg_iso_2="SM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="サンゴ語" WHERE lg_iso_2="SG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="セルビア語" WHERE lg_iso_2="SR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="セソト語" WHERE lg_iso_2="ST" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ツワナ語" WHERE lg_iso_2="TN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ショナ語" WHERE lg_iso_2="SN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="シンド語" WHERE lg_iso_2="SD" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="シンハラ語" WHERE lg_iso_2="SI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="シスワティ語" WHERE lg_iso_2="SS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スロバキア語" WHERE lg_iso_2="SK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スロベニア語" WHERE lg_iso_2="SL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ソマリア語" WHERE lg_iso_2="SO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スペイン語" WHERE lg_iso_2="ES" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スンダ語" WHERE lg_iso_2="SU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スワヒリ語" WHERE lg_iso_2="SW" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="スウェーデン語" WHERE lg_iso_2="SV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タガログ語" WHERE lg_iso_2="TL" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タジク語" WHERE lg_iso_2="TG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タミール語" WHERE lg_iso_2="TA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タタール語" WHERE lg_iso_2="TT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="テルグ語" WHERE lg_iso_2="TE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タイ語" WHERE lg_iso_2="TH" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チベット語" WHERE lg_iso_2="BO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ティグリニャ語" WHERE lg_iso_2="TI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="トンガ語" WHERE lg_iso_2="TO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ツォンガ語" WHERE lg_iso_2="TS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="トルコ語" WHERE lg_iso_2="TR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="トルクメン語" WHERE lg_iso_2="TK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="トゥイ語" WHERE lg_iso_2="TW" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウイグル語" WHERE lg_iso_2="UG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウクライナ語" WHERE lg_iso_2="UK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウルドゥー語" WHERE lg_iso_2="UR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウズベク語" WHERE lg_iso_2="UZ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ベトナム語" WHERE lg_iso_2="VI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウェールズ語" WHERE lg_iso_2="CY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ウォロフ語" WHERE lg_iso_2="WO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="コーサ語（ホサ語）" WHERE lg_iso_2="XH" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ヨルバ語" WHERE lg_iso_2="YO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ズールー語" WHERE lg_iso_2="ZU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ボスニア語" WHERE lg_iso_2="BS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アカン語" WHERE lg_iso_2="AK" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アラゴン語" WHERE lg_iso_2="AN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アヴァル語" WHERE lg_iso_2="AV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="バンバラ語" WHERE lg_iso_2="BM" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チェチェン語" WHERE lg_iso_2="CE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チャモロ語" WHERE lg_iso_2="CH" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クリー語" WHERE lg_iso_2="CR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="チュバシュ語" WHERE lg_iso_2="CV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ディベヒ語" WHERE lg_iso_2="DV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="エヴェ語" WHERE lg_iso_2="EE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="フルフルデ語" WHERE lg_iso_2="FF" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ヒリモトゥ語" WHERE lg_iso_2="HO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ハイチ語" WHERE lg_iso_2="HT" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ヘレロ語" WHERE lg_iso_2="HZ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イボ語" WHERE lg_iso_2="IG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="四川語" WHERE lg_iso_2="II" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="コンゴ語" WHERE lg_iso_2="KG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="キクユ語" WHERE lg_iso_2="KI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="クワンヤマ語" WHERE lg_iso_2="KJ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="カヌリ語" WHERE lg_iso_2="KR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="コミ語" WHERE lg_iso_2="KV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="コーンウォール語" WHERE lg_iso_2="KW" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ルクセンブルグ語" WHERE lg_iso_2="LB" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ガンダ語" WHERE lg_iso_2="LG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="リンブルグ語" WHERE lg_iso_2="LI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ルバ・カタンガ語" WHERE lg_iso_2="LU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="マーシャル語" WHERE lg_iso_2="MH" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ボークマール・ノルウェー語" WHERE lg_iso_2="NB" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="北ンデベレ語" WHERE lg_iso_2="ND" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ンドンガ語" WHERE lg_iso_2="NG" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ニーノシュク・ノルウェー語" WHERE lg_iso_2="NN" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="南ンデベレ語" WHERE lg_iso_2="NR" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ナバホ語" WHERE lg_iso_2="NV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ニャンジャ語" WHERE lg_iso_2="NY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オジブワ語" WHERE lg_iso_2="OJ" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="オセト語" WHERE lg_iso_2="OS" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="サルジニア語" WHERE lg_iso_2="SC" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="北サーミ語" WHERE lg_iso_2="SE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="タヒチ語" WHERE lg_iso_2="TY" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ベンダ語" WHERE lg_iso_2="VE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ワロン語" WHERE lg_iso_2="WA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ジャワ語" WHERE lg_iso_2="JV" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ポルトガル語" WHERE lg_iso_2="PT" AND lg_country_iso_2="BR";
UPDATE static_languages SET lg_name_ja="中国語" WHERE lg_iso_2="ZH" AND lg_country_iso_2="CN";
UPDATE static_languages SET lg_name_ja="インターリンガ（人口言語）" WHERE lg_iso_2="IA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="インターリンガ" WHERE lg_iso_2="IE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ラテン語" WHERE lg_iso_2="LA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="サンスクリット語" WHERE lg_iso_2="SA" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="ボラピュク語" WHERE lg_iso_2="VO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イディッシュ語" WHERE lg_iso_2="YI" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="アベスタ語" WHERE lg_iso_2="AE" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="教会スラブ語" WHERE lg_iso_2="CU" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="イード語" WHERE lg_iso_2="IO" AND lg_country_iso_2="";
UPDATE static_languages SET lg_name_ja="パーリ語" WHERE lg_iso_2="PI" AND lg_country_iso_2="";

